platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
    key_id: ENV["APPSTORE_KEY_ID"],
    issuer_id: ENV["APPSTORE_ISSUER_ID"],
    key_content: ENV['APPSTORE_P8'],
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

    #pilot(api_key: api_key)

    setup_ci if ENV['CI']

    get_certificates(
      api_key: api_key      
    )

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: ENV["IOS_BUNDLE_ID"],
      type: "appstore"
    )

    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end