org, repo = (ENV["GITHUB_REPOSITORY"]||"").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
    key_id: ENV["APPSTORE_KEY_ID"],
    issuer_id: ENV["APPSTORE_ISSUER_ID"],
    key_filepath: ENV['APPSTORE_P8'],
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

    pilot(api_key: api_key)

    setup_ci if ENV['CI']
    match(type: 'appstore',
          git_url: "git@github.com:#{match_org}/#{match_repo}.git",)
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end