
name: Build Unity iOS with Fastlane

on:
  workflow_dispatch:


jobs:
  unity-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS

      - name: Upload Xcode project artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS

  ios-build:
    runs-on: macos-latest
    needs: unity-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Xcode project artifact
        id: download_xcode
        uses: actions/download-artifact@v4
        with:
          name: ios-xcode-project
          path: build/ios

      - name: Set XCODE_PROJECT_PATH env
        run: echo "XCODE_PROJECT_PATH=build/ios" >> $GITHUB_ENV

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Ruby gems
        run: bundle install

      - name: Install CocoaPods
        run: |
          if [ -f "$XCODE_PROJECT_PATH/Podfile" ]; then
            bundle exec pod install --project-directory="$XCODE_PROJECT_PATH"
          fi

      - name: Run Fastlane (beta lane, upload to TestFlight)
        run: bundle exec fastlane ios beta
        working-directory: ${{ env.XCODE_PROJECT_PATH }}
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APPLE_CONNECT_EMAIL }}
          APP_IDENTIFIER: ${{ secrets.IOS_BUNDLE_ID }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          IOS_APP_NAME: ${{ secrets.IOS_APP_NAME }}
          APP_VERSION: ${{ secrets.APP_VERSION }}
